const especialidades = [
  "Alergólogo",
  "Anestesiólogo",
  "Cardiólogo",
  "Cirujano",
  "Dermatólogo",
  "Endocrinólogo",
  "Gastroenterólogo",
  "Geriatra",
  "Ginecólogo",
  "Hematólogo",
  "Infectólogo",
  "Médico de familia",
  "Neurólogo",
  "Nutricionista",
  "Odontólogo",
  "Oftalmólogo",
  "Oncólogo",
  "Otorrinolaringólogo",
  "Pediatra",
  "Psicólogo",
  "Psiquiatra",
  "Radiólogo",
  "Reumatólogo",
  "Traumatólogo",
  "Urólogo",
];

export default especialidades;
